# version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-net

  # frontend-admin:
  #   build: ./frontend/admin
  #   ports:
  #     - "3001:3001"
  #   networks:
  #     - app-net
  
  # frontend-user:
  #   build: ./frontend/user
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app-net

networks:
  app-net: