---
spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https//kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: 1787ceca99a6e6af61ca37db420f69db
            client-name: Kakao
            client-secret: Of60eYA1xMU3hTrQEtL9CfsU3pMXKGvf
            redirect-uri: http://localhost:8080/api/kakao/callback
            scope:
              - profile
              - account_email
          naver:
            authorization-grant-type: authorization_code
            client-id: HbcbABXza6tp9n9hyHrg
            client-name: Naver
            client-secret: zNvzObH8Od
            redirect-uri: http://localhost:8080/api/naver/callback
            scope:
              - name
              - email
---
spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https//kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: 1787ceca99a6e6af61ca37db420f69db
            client-name: Kakao
            client-secret: Of60eYA1xMU3hTrQEtL9CfsU3pMXKGvf
            redirect-uri: http://localhost:8080/api/kakao/callback
            scope:
              - profile
              - account_email
          naver:
            authorization-grant-type: authorization_code
            client-id: HbcbABXza6tp9n9hyHrg
            client-name: Naver
            client-secret: zNvzObH8Od
            redirect-uri: http://localhost:8080/api/naver/callback
            scope:
              - name
              - email
---
spring:
  config:
    activate:
      on-profile: prod
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https//kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: 1787ceca99a6e6af61ca37db420f69db
            client-name: Kakao
            client-secret: Of60eYA1xMU3hTrQEtL9CfsU3pMXKGvf
            redirect-uri: http://localhost:8080/api/kakao/callback
            scope:
              - profile
              - account_email
          naver:
            authorization-grant-type: authorization_code
            client-id: HbcbABXza6tp9n9hyHrg
            client-name: Naver
            client-secret: zNvzObH8Od
            redirect-uri: http://localhost:8080/api/naver/callback
            scope:
              - name
              - email