---
spring:
  config:
    activate:
      on-profile: local
  titan:
    service: service
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod