---
server:
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/xml
      - text/plain
      - text/css
      - text/javascript
      - application/javascript
      - application/json
    min-response-size: 1024
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true
        secure: false
      timeout: 30m
spring:
  profiles:
    active: local
    group:
      dev: dev
      local: local
      prod: prod
    include:
      - oauth
      - titan
    resources:
      static-locations: files:./src/main/resources/statics/
---
cloud:
  aws:
    #    s3:
    #      bucket: hr-portal-backend
    region:
      static: ap-southeast-2
logging:
  config: classpath:log4j2.yml
mybatis:
  configuration:
    jdbc-type-for-null: "NULL"
    map-underscore-to-camel-case: true
  mapper-locations: /mapper/**/*.xml
  type-aliases-package: com.thesys.titan.common.vo,com.thesys.titan.**.vo
jpa:
  hibernate:
    ddl-auto: update # (create, create-drop, update, validate, none)
  show-sql: true
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
  open-in-view: false
# JPA 엔티티 감사(Auditing) 기능을 위한 설정 (필요 시)
data:
  jpa:
    repositories:
      enabled: true

---
##### local #####
spring:
  cloud.vault:
    app-role:
      role-id: 5cf80ec1-c717-f9c1-540a-efbce42b01b1
      secret-id: c95a6b20-4322-0468-2109-b07b4febca4a
    authentication: approle
    kv:
      backend: secret
      default-context: thesys/dev
      enabled: true
    ssl:
      trust-store: classpath:truststore.jks
      trust-store-password: changeit
    uri: https://mangchinas.synology.me:8200
  config:
    activate:
      on-profile: local
    import: vault://
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SELECT 1
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 1
    # url: jdbc:mysql://thesys.biz:33306/thesys?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  primary:
    datasource:
      hikari:
        maximum-pool-size: 10
        pool-name: titan-primary-cp
  secondary:
    datasource:
      hikari:
        maximum-pool-size: 10
        pool-name: titan-secondary-cp
  web:
    resources:
      static-locations: file:./src/main/resources/static/
---
##### dev #####
spring:
  cloud.vault:
    app-role:
      role-id: 5cf80ec1-c717-f9c1-540a-efbce42b01b1
      secret-id: c95a6b20-4322-0468-2109-b07b4febca4a
    authentication: approle
    kv:
      backend: secret
      default-context: thesys/dev
      enabled: true
    ssl:
      trust-store: classpath:truststore.jks
      trust-store-password: changeit
    uri: https://mangchinas.synology.me:8200
  config:
    activate:
      on-profile: dev
    import: vault://
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SELECT 1
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 1
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  primary:
    datasource:
      hikari:
        maximum-pool-size: 10
        pool-name: titan-primary-cp
  secondary:
    datasource:
      hikari:
        maximum-pool-size: 10
        pool-name: titan-secondary-cp
  web:
    resources:
      static-locations: file:./src/main/resources/static/
---
##### prod #####
spring:
  cloud.vault:
    app-role:
      role-id: 5cf80ec1-c717-f9c1-540a-efbce42b01b1
      secret-id: c95a6b20-4322-0468-2109-b07b4febca4a
    authentication: approle
    kv:
      backend: secret
      default-context: thesys/dev
      enabled: true
    ssl:
      trust-store: classpath:truststore.jks
      trust-store-password: changeit
    uri: https://mangchinas.synology.me:8200
  config:
    activate:
      on-profile: prod
    import: vault://
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SELECT 1
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 1
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  primary:
    datasource:
      hikari:
        maximum-pool-size: 10
        pool-name: titan-primary-cp
  secondary:
    datasource:
      hikari:
        maximum-pool-size: 10
        pool-name: titan-secondary-cp
  web:
    resources:
      static-locations: file:./src/main/resources/static/
---
springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
    path: /api-docs
    version: OPENAPI_3_1
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: /api/**
  swagger-ui:
    disable-swagger-default-url: true
    doc-expansion: none
    operations-sorter: alpha
    path: /swagger-ui.html
    tags-sorter: alpha
